######################################################################
# Automatically generated by qmake (3.0) Thu Dec 21 20:28:04 2017
######################################################################

TEMPLATE = app
TARGET = Projet-Reversi
INCLUDEPATH += .

# Input
QT += widgets
HEADERS += Plateau.h Player.h Vue.h VueGUI.h
SOURCES += Main.cpp Plateau.cpp Player.cpp Vue.cpp VueGUI.cpp
